### PR TITLE
Clean up npm package

### PR DESCRIPTION
**Pull request by ai**
This package is very useful and its content is very small.

Unfortunately, npm package contains many development files. This development files even bigger than actual useful package content :D. Let’s remove them to make `node_module` smaller.

Also, these files raise warnings on out build CI server:

```
warning: CRLF will be replaced by LF in node_modules/void-elements/.gitattributes.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/.npmignore.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/.travis.yml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/LICENSE.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/README.md.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/pre-publish.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/void-elements/test/index.js.
The file will have its original line endings in your working directory.
```

@ForbesLindesay @TimothyGu

### CODE REVIEW

**Comment by ai** [comment]
Other way is to set `package.files`

**Comment by ai** [comment]
@hemanth thanks :tada: waiting for release :package:

**Comment by ForbesLindesay** [comment]
I recommend fixing the config on your build server. You should not be getting warnings for line ending changes in node_modules packages.

**Comment by ai** [comment]
The issue here with unnecessary files in the package. Warnings just helped to find them.

**Pull request merged**
